/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Janelas;


import DAO.VendasDAO;
import Model.VendaTableModel;
import Objetos.CadastroVendas;
import Objetos.Usuario;
import java.util.Date;

/**
 *
 * @author leonardo.hpavan
 */
public class CadastroVenda extends javax.swing.JFrame {
            VendaTableModel modelo = new VendaTableModel();
    /**
     * Creates new form CadastoVenda
     */
    public CadastroVenda() {
        initComponents();
    }
            
    public CadastroVenda(Usuario u) {
        initComponents();
        jTVenda.setModel(modelo);
        this.setLocationRelativeTo(null);
        
        if ("Admin".equals(u.getTipo())){
            jBUsuarios.setEnabled(true);
        } else {
            jBUsuarios.setEnabled(false);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTData_Ult_Venda = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jBCadastrar = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jBAlterar = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jBExcluir = new javax.swing.JButton();
        jTNmrNFEntrada = new javax.swing.JTextField();
        jTCNPJ_drogaria = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jTData_Entrega = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTValor_Total = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTCusto_Total = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTTotal_Nota = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTForma_Pagamento = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTVenda = new javax.swing.JTable();
        jBUsuarios = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jTData_Ult_Venda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTData_Ult_VendaActionPerformed(evt);
            }
        });

        jLabel7.setText("Total da Nota");

        jBCadastrar.setText("Cadastrar");
        jBCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBCadastrarActionPerformed(evt);
            }
        });

        jLabel8.setText("Forma de Pagamento");

        jBAlterar.setText("Alterar");
        jBAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBAlterarActionPerformed(evt);
            }
        });

        jLabel9.setText("Data da Última Venda");

        jBExcluir.setText("Excluir");
        jBExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBExcluirActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Cadastro de Venda");

        jLabel2.setText("Número Nota Fiscal de Entrada");

        jLabel3.setText("CNPJ Drogaria");

        jTCusto_Total.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTCusto_TotalActionPerformed(evt);
            }
        });

        jLabel4.setText("Data de Entrega");

        jLabel5.setText("Valor Total");

        jLabel6.setText("Custo Total");

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Consultar");

        jTVenda.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTVenda.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTVendaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTVenda);

        jBUsuarios.setText("Usuarios");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jBCadastrar)
                                .addComponent(jLabel9)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTNmrNFEntrada)
                                    .addComponent(jTCNPJ_drogaria)
                                    .addComponent(jTData_Entrega)
                                    .addComponent(jTValor_Total)
                                    .addComponent(jTCusto_Total)
                                    .addComponent(jTTotal_Nota)
                                    .addComponent(jTForma_Pagamento)
                                    .addComponent(jTData_Ult_Venda, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(4, 4, 4)
                                .addComponent(jBAlterar)
                                .addGap(39, 39, 39)
                                .addComponent(jBExcluir)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 31, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 420, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jBUsuarios)
                .addGap(15, 15, 15))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jTNmrNFEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jTCNPJ_drogaria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jTData_Entrega, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jTValor_Total, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(jTCusto_Total, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(jTTotal_Nota, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(jTForma_Pagamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(jTData_Ult_Venda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jBExcluir)
                            .addComponent(jBAlterar)
                            .addComponent(jBCadastrar)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jBUsuarios)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTData_Ult_VendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTData_Ult_VendaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTData_Ult_VendaActionPerformed

    private void jBCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBCadastrarActionPerformed
        CadastroVendas c = new CadastroVendas();
        VendasDAO ddao = new VendasDAO();
        
        c.setNmr_nf_entrada(Integer.parseInt(jTNmrNFEntrada.getText()));
        c.setCnpj_drogaria(jTCNPJ_drogaria.getText());
        c.setData_entrega(parseDate (jTData_Entrega.getText()));
        c.setValor_total(Double.valueOf(jTValor_Total.getText()));
        c.setCusto_total(Double.valueOf(jTCusto_Total.getText()));
        c.setTotal_nota(Double.valueOf(jTTotal_Nota.getText()));
        c.setForma_pagamento(jTForma_Pagamento.getText());
        c.setData_ult_venda(parseDate(jTData_Ult_Venda.getText()));
        
        ddao.create(c);
        modelo.recarregaTabela();
        limpaCampos();
    }//GEN-LAST:event_jBCadastrarActionPerformed

    private void jTCusto_TotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTCusto_TotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTCusto_TotalActionPerformed

    private void jBAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBAlterarActionPerformed
         if (jTVenda.getSelectedRow() != -1){
            modelo.setValueAt(jTNmrNFEntrada.getText(), jTVenda.getSelectedRow(), 0);
            modelo.setValueAt(jTCNPJ_drogaria.getText(), jTVenda.getSelectedRow(), 1);
            modelo.setValueAt(jTData_Entrega.getText(), jTVenda.getSelectedRow(), 2);
            modelo.setValueAt(jTValor_Total.getText(), jTVenda.getSelectedRow(), 3);
            modelo.setValueAt(jTCusto_Total.getText(), jTVenda.getSelectedRow(), 4);
            modelo.setValueAt(jTTotal_Nota.getText(), jTVenda.getSelectedRow(), 5);
            modelo.setValueAt(jTForma_Pagamento.getText(), jTVenda.getSelectedRow(), 6);
            modelo.setValueAt(jTData_Ult_Venda.getText(), jTVenda.getSelectedRow(), 7);
         }
    }//GEN-LAST:event_jBAlterarActionPerformed

    private void jBExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBExcluirActionPerformed
        if (jTVenda.getSelectedRow() != -1){
            CadastroVendas c = modelo.pegaDadosLinha(jTVenda.getSelectedRow());
            VendasDAO ddao = new VendasDAO();
            ddao.delete(c);
            modelo.recarregaTabela();
        }
    }//GEN-LAST:event_jBExcluirActionPerformed

    private void jTVendaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTVendaMouseClicked
        if (jTVenda.getSelectedRow() != -1){
            CadastroVendas c = modelo.pegaDadosLinha(jTVenda.getSelectedRow());
            jTNmrNFEntrada.setText(String.valueOf(c.getNmr_nf_entrada()));
            jTCNPJ_drogaria.setText(c.getCnpj_drogaria());
            jTData_Entrega.setText(String.valueOf(c.getData_entrega()));
            jTValor_Total.setText(String.valueOf(c.getValor_total()));
            jTCusto_Total.setText(String.valueOf(c.getCusto_total()));
            jTTotal_Nota.setText(String.valueOf(c.getTotal_nota()));
            jTForma_Pagamento.setText(c.getForma_pagamento());
            jTData_Ult_Venda.setText(String.valueOf(c.getData_ult_venda()));
        }
    }//GEN-LAST:event_jTVendaMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroVenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroVenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroVenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroVenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastroVenda().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBAlterar;
    private javax.swing.JButton jBCadastrar;
    private javax.swing.JButton jBExcluir;
    private javax.swing.JButton jBUsuarios;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTCNPJ_drogaria;
    private javax.swing.JTextField jTCusto_Total;
    private javax.swing.JTextField jTData_Entrega;
    private javax.swing.JTextField jTData_Ult_Venda;
    private javax.swing.JTextField jTForma_Pagamento;
    private javax.swing.JTextField jTNmrNFEntrada;
    private javax.swing.JTextField jTTotal_Nota;
    private javax.swing.JTextField jTValor_Total;
    private javax.swing.JTable jTVenda;
    // End of variables declaration//GEN-END:variables
    
    private void limpaCampos() {
        jTNmrNFEntrada.setText("");
        jTCNPJ_drogaria.setText("");
        jTData_Entrega.setText("");
        jTValor_Total.setText("");
        jTCusto_Total.setText("");
        jTTotal_Nota.setText("");
        jTForma_Pagamento.setText("");
        jTData_Ult_Venda.setText("");

    
}

    private Date parseDate(String text) {
         if (text == null || text.trim().isEmpty()) {
        return new Date(); // data atual
    }
    try {
        java.text.SimpleDateFormat sdf = new java.text.SimpleDateFormat("dd/MM/yyyy");
        return sdf.parse(text);
    } catch (java.text.ParseException e) {
        System.err.println("Erro ao converter data: " + text);
        return new Date(); // fallback
    }
    }

}
