/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Janelas;

import DAO.CompraDAO;
import Model.CompraTableModel;
import Objetos.CadastroCompras;
import java.time.Instant;
import java.util.Date;

/**
 *
 * @author leonardo.hpavan
 */
public class CadastroCompra extends javax.swing.JFrame {
            CompraTableModel modelo = new CompraTableModel();
    /**
     * Creates new form CadastroCompra
     */
    public CadastroCompra() {
        initComponents();
        jTCompra.setModel(modelo);
        this.setLocationRelativeTo(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jTNumNFEntrada = new javax.swing.JTextField();
        jTCNPJ_lab = new javax.swing.JTextField();
        jTData_Entrada = new javax.swing.JTextField();
        jTValor_Total = new javax.swing.JTextField();
        jTCusto_Total = new javax.swing.JTextField();
        jTTotal_Nota = new javax.swing.JTextField();
        jTForma_Pagamento = new javax.swing.JTextField();
        jTData_Ult_Compra = new javax.swing.JTextField();
        jBCadastrar = new javax.swing.JButton();
        jBAlterar = new javax.swing.JButton();
        jBExcluir = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTCompra = new javax.swing.JTable();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Cadastro de Compra");

        jLabel2.setText("Número Nota Fisca de Entrada");

        jLabel3.setText("CNPJ Laboratório");

        jLabel4.setText("Data de Entrada");

        jLabel5.setText("Valor Total");

        jLabel6.setText("Custo Total");

        jLabel7.setText("Total da Nota");

        jLabel8.setText("Forma de Pagamento");

        jLabel9.setText("Data da Última Compra");

        jTCusto_Total.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTCusto_TotalActionPerformed(evt);
            }
        });

        jTData_Ult_Compra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTData_Ult_CompraActionPerformed(evt);
            }
        });

        jBCadastrar.setText("Cadastrar");
        jBCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBCadastrarActionPerformed(evt);
            }
        });

        jBAlterar.setText("Alterar");
        jBAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBAlterarActionPerformed(evt);
            }
        });

        jBExcluir.setText("Excluir");
        jBExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBExcluirActionPerformed(evt);
            }
        });

        jTCompra.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTCompra.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTCompraMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTCompra);

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Consulta");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(25, 25, 25)
                                .addComponent(jBCadastrar)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jTNumNFEntrada)
                                .addComponent(jTCNPJ_lab)
                                .addComponent(jTData_Entrada)
                                .addComponent(jTValor_Total)
                                .addComponent(jTCusto_Total)
                                .addComponent(jTTotal_Nota)
                                .addComponent(jTForma_Pagamento)
                                .addComponent(jTData_Ult_Compra, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jBAlterar)
                                .addGap(63, 63, 63)
                                .addComponent(jBExcluir)
                                .addGap(19, 19, 19))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(134, 134, 134)
                        .addComponent(jLabel1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1)
                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel10))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jTNumNFEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jTCNPJ_lab, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jTData_Entrada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jTValor_Total, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(jTCusto_Total, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(jTTotal_Nota, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(jTForma_Pagamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(jTData_Ult_Compra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jBCadastrar)
                            .addComponent(jBExcluir)
                            .addComponent(jBAlterar)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTCusto_TotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTCusto_TotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTCusto_TotalActionPerformed

    private void jTData_Ult_CompraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTData_Ult_CompraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTData_Ult_CompraActionPerformed

    private void jBCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBCadastrarActionPerformed
        CadastroCompras c = new CadastroCompras();
        CompraDAO cdao = new CompraDAO();
        
        c.setNum_nf_entrada(Integer.parseInt(jTNumNFEntrada.getText()));
        c.setCnpj_lab(jTCNPJ_lab.getText());
        c.setData_entrada(parseDate (jTData_Entrada.getText()));
        c.setValor_total(Double.valueOf(jTValor_Total.getText()));
        c.setCusto_total(Double.valueOf(jTCusto_Total.getText()));
        c.setTotal_nota(Double.valueOf(jTTotal_Nota.getText()));
        c.setForma_pagamento(jTForma_Pagamento.getText());
        c.setData_ult_compra(parseDate(jTData_Ult_Compra.getText()));
        
        cdao.create(c);
        modelo.recarregaTabela();
        
    }//GEN-LAST:event_jBCadastrarActionPerformed

    private void jBAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBAlterarActionPerformed
        if (jTCompra.getSelectedRow() != -1){
            modelo.setValueAt(jTNumNFEntrada.getText(), jTCompra.getSelectedRow(), 0);
            modelo.setValueAt(jTCNPJ_lab.getText(), jTCompra.getSelectedRow(), 1);
            modelo.setValueAt(jTData_Entrada.getText(), jTCompra.getSelectedRow(), 2);
            modelo.setValueAt(jTValor_Total.getText(), jTCompra.getSelectedRow(), 3);
            modelo.setValueAt(jTCusto_Total.getText(), jTCompra.getSelectedRow(), 4);
            modelo.setValueAt(jTTotal_Nota.getText(), jTCompra.getSelectedRow(), 5);
            modelo.setValueAt(jTForma_Pagamento.getText(), jTCompra.getSelectedRow(), 6);
            modelo.setValueAt(jTData_Ult_Compra.getText(), jTCompra.getSelectedRow(), 7);
         }
    }//GEN-LAST:event_jBAlterarActionPerformed

    private void jBExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBExcluirActionPerformed
        if (jTCompra.getSelectedRow() != -1){
            CadastroCompras c = modelo.pegaDadosLinha(jTCompra.getSelectedRow());
            CompraDAO cdao = new CompraDAO();
            cdao.delete(c);
            modelo.recarregaTabela();
        }
    }//GEN-LAST:event_jBExcluirActionPerformed

    private void jTCompraMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTCompraMouseClicked
        if (jTCompra.getSelectedRow() != -1){
            CadastroCompras c = modelo.pegaDadosLinha(jTCompra.getSelectedRow());
            jTNumNFEntrada.setText(String.valueOf(c.getNum_nf_entrada()));
            jTCNPJ_lab.setText(c.getCnpj_lab());
            jTData_Entrada.setText(String.valueOf(c.getData_entrada()));
            jTValor_Total.setText(String.valueOf(c.getValor_total()));
            jTCusto_Total.setText(String.valueOf(c.getCusto_total()));
            jTTotal_Nota.setText(String.valueOf(c.getTotal_nota()));
            jTForma_Pagamento.setText(c.getForma_pagamento());
            jTData_Ult_Compra.setText(String.valueOf(c.getData_ult_compra()));
        }
    }//GEN-LAST:event_jTCompraMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroCompra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroCompra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroCompra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroCompra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastroCompra().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBAlterar;
    private javax.swing.JButton jBCadastrar;
    private javax.swing.JButton jBExcluir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTCNPJ_lab;
    private javax.swing.JTable jTCompra;
    private javax.swing.JTextField jTCusto_Total;
    private javax.swing.JTextField jTData_Entrada;
    private javax.swing.JTextField jTData_Ult_Compra;
    private javax.swing.JTextField jTForma_Pagamento;
    private javax.swing.JTextField jTNumNFEntrada;
    private javax.swing.JTextField jTTotal_Nota;
    private javax.swing.JTextField jTValor_Total;
    // End of variables declaration//GEN-END:variables
    
    private void limpaCampos() {
        jTNumNFEntrada.setText("");
        jTCNPJ_lab.setText("");
        jTData_Entrada.setText("");
        jTValor_Total.setText("");
        jTCusto_Total.setText("");
        jTTotal_Nota.setText("");
        jTForma_Pagamento.setText("");
        jTData_Ult_Compra.setText("");

    
}

    private Date parseDate(String text) {
         if (text == null || text.trim().isEmpty()) {
        return new Date(); // data atual
    }
    try {
        java.text.SimpleDateFormat sdf = new java.text.SimpleDateFormat("dd/MM/yyyy");
        return sdf.parse(text);
    } catch (java.text.ParseException e) {
        System.err.println("Erro ao converter data: " + text);
        return new Date(); // fallback
    }
    }
    
}

