/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Janelas;

import DAO.DrogariaDAO;
import DAO.LaboratorioDAO;
import Model.LaboratorioTableModel;
import Objetos.Laboratorio;
import java.awt.Color;



/**
 *
 * @author william.flima4
 */
public class CadastroLaboratorio extends javax.swing.JFrame {
    LaboratorioTableModel modelo = new LaboratorioTableModel();
    
    
    public CadastroLaboratorio() {
        initComponents();
        jTLaboratorio.setModel(modelo);
        modelo.recarregaTabela();
        this.setLocationRelativeTo(null);
        getContentPane().setBackground(Color.LIGHT_GRAY);
      
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLCNPJ = new javax.swing.JLabel();
        jLNome = new javax.swing.JLabel();
        jLIE = new javax.swing.JLabel();
        jLCEP = new javax.swing.JLabel();
        jLCidade = new javax.swing.JLabel();
        jLEstado = new javax.swing.JLabel();
        jLBairro = new javax.swing.JLabel();
        jLRua = new javax.swing.JLabel();
        jTCnpjLab = new javax.swing.JTextField();
        jTNomeLab = new javax.swing.JTextField();
        jTIeLab = new javax.swing.JTextField();
        jTCepLab = new javax.swing.JTextField();
        jTBairroLab = new javax.swing.JTextField();
        jTRuaLab = new javax.swing.JTextField();
        jTCidadeLab = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTNumero = new javax.swing.JTextField();
        jTEstado = new javax.swing.JTextField();
        jBCadastroLab = new javax.swing.JButton();
        jBAlterarLab = new javax.swing.JButton();
        jBDeletarLab = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTLaboratorio = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Cadastro de laboratórios fornecedores");

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLCNPJ.setText("CNPJ");

        jLNome.setText("Nome");

        jLIE.setText("IE");

        jLCEP.setText("CEP");

        jLCidade.setText("Cidade");

        jLEstado.setText("Estado");

        jLBairro.setText("Bairro");

        jLRua.setText("Rua");

        jTBairroLab.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTBairroLabActionPerformed(evt);
            }
        });

        jLabel2.setText("Número");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLCEP)
                                    .addComponent(jLIE))
                                .addGap(22, 22, 22)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTIeLab, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 379, Short.MAX_VALUE)
                                    .addComponent(jTCepLab)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLNome)
                                    .addComponent(jLCNPJ))
                                .addGap(10, 10, 10)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTCnpjLab)
                                    .addComponent(jTNomeLab)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLCidade)
                                    .addComponent(jLRua)
                                    .addComponent(jLEstado)
                                    .addComponent(jLBairro))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addComponent(jTCidadeLab))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jTRuaLab, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jTBairroLab)))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTEstado))))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(5, 5, 5)
                        .addComponent(jTNumero)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLCNPJ)
                    .addComponent(jTCnpjLab, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTNomeLab, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLNome))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTIeLab, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLIE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTCepLab, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLCEP))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLEstado)
                    .addComponent(jTEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLCidade)
                    .addComponent(jTCidadeLab, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTBairroLab, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLBairro))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLRua)
                    .addComponent(jTRuaLab, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jTNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(41, Short.MAX_VALUE))
        );

        jBCadastroLab.setText("Cadastrar");
        jBCadastroLab.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBCadastroLabActionPerformed(evt);
            }
        });

        jBAlterarLab.setText("Alterar");
        jBAlterarLab.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBAlterarLabActionPerformed(evt);
            }
        });

        jBDeletarLab.setText("Excluir");
        jBDeletarLab.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBDeletarLabActionPerformed(evt);
            }
        });

        jTLaboratorio.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTLaboratorio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTLaboratorioMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTLaboratorio);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Consulta");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 438, Short.MAX_VALUE)
                            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jBCadastroLab)
                        .addGap(76, 76, 76)
                        .addComponent(jBAlterarLab)
                        .addGap(81, 81, 81)
                        .addComponent(jBDeletarLab)))
                .addGap(18, 20, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 427, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(25, 25, 25))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jBCadastroLab)
                            .addComponent(jBAlterarLab)
                            .addComponent(jBDeletarLab))
                        .addGap(22, 22, 22))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addContainerGap())))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTBairroLabActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTBairroLabActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTBairroLabActionPerformed

    private void jBCadastroLabActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBCadastroLabActionPerformed
        Laboratorio l = new Laboratorio();
        LaboratorioDAO dao = new LaboratorioDAO();
        
        l.setCnpj(jTCnpjLab.getText());
        l.setNome(jTNomeLab.getText());
        l.setIE(jTIeLab.getText());
        l.setCep(jTCepLab.getText());
        l.setEstado(jTEstado.getText());
        l.setCidade(jTCidadeLab.getText());
        l.setBairro(jTBairroLab.getText());
        l.setRua(jTRuaLab.getText());
        l.setNumero(Integer.parseInt(jTNumero.getText()));
        
        dao.create(l);
        modelo.recarregaTabela();
        limpaCampos();
    }//GEN-LAST:event_jBCadastroLabActionPerformed

    private void jBAlterarLabActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBAlterarLabActionPerformed
        if (jTLaboratorio.getSelectedRow() != -1){
            modelo.setValueAt(jTCnpjLab.getText(), jTLaboratorio.getSelectedRow(), 0);
            modelo.setValueAt(jTNomeLab.getText(), jTLaboratorio.getSelectedRow(), 1);
            modelo.setValueAt(jTIeLab.getText(), jTLaboratorio.getSelectedRow(), 2);
            modelo.setValueAt(jTCepLab.getText(), jTLaboratorio.getSelectedRow(), 3);
            modelo.setValueAt(jTEstado.getText(), jTLaboratorio.getSelectedRow(), 4);
            modelo.setValueAt(jTCidadeLab.getText(), jTLaboratorio.getSelectedRow(), 5);
            modelo.setValueAt(jTBairroLab.getText(), jTLaboratorio.getSelectedRow(), 6);
            modelo.setValueAt(jTRuaLab.getText(), jTLaboratorio.getSelectedRow(), 7);
            modelo.setValueAt(jTNumero.getText(), jTLaboratorio.getSelectedRow(), 8);
            
            Laboratorio l = modelo.pegaDadosLinha(jTLaboratorio.getSelectedRow());
            LaboratorioDAO dao = new LaboratorioDAO();
            dao.update(l);
            limpaCampos();
            modelo.recarregaTabela();
            
        }
    }//GEN-LAST:event_jBAlterarLabActionPerformed

    private void jBDeletarLabActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBDeletarLabActionPerformed
        if (jTLaboratorio.getSelectedRow() != -1){
            Laboratorio p = modelo.pegaDadosLinha(jTLaboratorio.getSelectedRow());
            LaboratorioDAO dao = new LaboratorioDAO();
            dao.delete(p);
            modelo.recarregaTabela();
        }
    }//GEN-LAST:event_jBDeletarLabActionPerformed

    private void jTLaboratorioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTLaboratorioMouseClicked
        if (jTLaboratorio.getSelectedRow() != -1){
            Laboratorio l = modelo.pegaDadosLinha(jTLaboratorio.getSelectedRow());
            jTNomeLab.setText(l.getNome());
            jTIeLab.setText(l.getIE());
            jTCepLab.setText(l.getCep());
            jTEstado.setText(l.getEstado());
            jTCidadeLab.setText(l.getCidade());
            jTBairroLab.setText(l.getBairro());
            jTRuaLab.setText(l.getRua());
            jTNumero.setText(String.valueOf(l.getNumero()));
            
        }
    }//GEN-LAST:event_jTLaboratorioMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroLaboratorio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroLaboratorio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroLaboratorio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroLaboratorio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastroLaboratorio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBAlterarLab;
    private javax.swing.JButton jBCadastroLab;
    private javax.swing.JButton jBDeletarLab;
    private javax.swing.JLabel jLBairro;
    private javax.swing.JLabel jLCEP;
    private javax.swing.JLabel jLCNPJ;
    private javax.swing.JLabel jLCidade;
    private javax.swing.JLabel jLEstado;
    private javax.swing.JLabel jLIE;
    private javax.swing.JLabel jLNome;
    private javax.swing.JLabel jLRua;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTBairroLab;
    private javax.swing.JTextField jTCepLab;
    private javax.swing.JTextField jTCidadeLab;
    private javax.swing.JTextField jTCnpjLab;
    private javax.swing.JTextField jTEstado;
    private javax.swing.JTextField jTIeLab;
    private javax.swing.JTable jTLaboratorio;
    private javax.swing.JTextField jTNomeLab;
    private javax.swing.JTextField jTNumero;
    private javax.swing.JTextField jTRuaLab;
    // End of variables declaration//GEN-END:variables

    private void limpaCampos() {
        jTCnpjLab.setText("");
        jTNomeLab.setText("");
        jTIeLab.setText("");
        jTCepLab.setText("");
        jTCidadeLab.setText("");
        jTBairroLab.setText("");
        jTRuaLab.setText("");
        jTNumero.setText("");
                
    }
}
